name: Create feature docs
on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    if: ${{ github.repository == 'AlexMan123456/eslint-plugin' }}
    uses: AlexMan123456/github-actions/.github/workflows/create-feature-docs.yml@78be199abfba7efedbc8a151b98a58963038cad7 # v4.0.4
    secrets:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
