name: Create feature docs
on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-feature-docs:
    if: ${{ github.repository == 'AlexMan123456/eslint-plugin' }}
    uses: AlexMan123456/github-actions/.github/workflows/create-feature-docs.yml@134246f0ec5c5b7efad0b3e332a68c387132b84f # v3.1.2
    secrets:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
